version: "3.1"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  corereactredux:
    build: .
    ports:
      - 80:80
    environment:
      - ConnectionStrings:DefaultConnection=mongodb://mongo:27017
    depends_on:
      - mongo
